# Googol Vibe - Terraform Outputs
# Export values for application configuration

output "project_id" {
  description = "GCP Project ID"
  value       = local.project_id
}

output "project_number" {
  description = "GCP Project Number"
  value       = var.billing_account != "" ? google_project.googol_vibe[0].number : "See Google Cloud Console"
}

output "enabled_apis" {
  description = "List of enabled Google APIs"
  value = [
    "gmail.googleapis.com",
    "calendar-json.googleapis.com",
    "drive.googleapis.com",
    "people.googleapis.com",
    "tasks.googleapis.com",
  ]
}

output "oauth_brand_name" {
  description = "OAuth brand resource name"
  value       = google_iap_brand.googol_vibe.name
}

output "oauth_client_id" {
  description = "OAuth Client ID (partial - download full credentials from Console)"
  value       = google_iap_client.googol_vibe_desktop.client_id
  sensitive   = true
}

output "credentials_download_url" {
  description = "URL to download OAuth credentials"
  value       = "https://console.cloud.google.com/apis/credentials?project=${local.project_id}"
}

output "consent_screen_url" {
  description = "URL to configure OAuth consent screen"
  value       = "https://console.cloud.google.com/apis/credentials/consent?project=${local.project_id}"
}

output "credentials_path" {
  description = "Where to save the downloaded credentials"
  value       = "~/.googol-vibe/credentials.json"
}

# Generate .env file content
output "env_file_content" {
  description = "Content for .env file (replace placeholders)"
  value       = <<-EOT
    # Googol Vibe Configuration
    # Generated by Terraform

    GOOGLE_PROJECT_ID=${local.project_id}
    GOOGLE_CLIENT_ID=<download from Console>
    GOOGLE_CLIENT_SECRET=<download from Console>

    # Paths (defaults work for most users)
    CREDENTIALS_PATH=~/.googol-vibe/credentials.json
    TOKEN_PATH=~/.googol-vibe/tokens/
  EOT
}
